RpcServer:
  network: "tcp"
  host: "0.0.0.0"
  port: "6808"
  http_port: "6809"

SideCar:
  InflowAddr:
    protocol_type: "http"
    bind_network: "tcp"
    bind_address: "0.0.0.0:6080"
    bind_ip: ""
    bind_port: ""
    target_protocol_type: "http"
    target_address: "127.0.0.1:80"
    target_dial_timeout: 1
    target_keep_alive: 30
    target_idle_conn_timeout: 60
    target_max_idle_conns_per_host: 200
  OutflowAddr:
    bind_protocol_type: "http"
    bind_network: "tcp"
    bind_address: "0.0.0.0:6081"
    bind_ip: ""
    bind_port: ""
    target_protocol_type: "http"
    target_address: "127.0.0.1:80"
    target_dial_timeout: 1
    target_keep_alive: 30
    target_idle_conn_timeout: 60
    target_max_idle_conns_per_host: 200

LogConfig:
  debug: true
  log_dir: "./log_dir"
  stdout_filename: "log_file.log"
  encoding: ""

Registry:
  type: "nmdir"
  host: "127.0.0.1"
  port: "6810"
  renew: 5

WhiteList:
  enable: true
  allow_list:
    127.0.0.1: true
    127.0.0.2: true
    192.168.10.67: true
    192.168.10.99: true
  allow_list_mask: ["172.17.0.0/16", "172.17.0.0/26" ]

BlackList:
  enable: false
  no_allow_list:
    127.0.0.1: true
    127.0.0.2: true
  no_allow_list_mask: ["172.17.0.0/16", "172.17.0.0/26" ]

Breaker:
  serial_error_numbers: 5 # 默认连续错误次数触发熔断
  error_percent: 1 # 错误数占总请求数的百分比熔断，1-100，10%
  max_request: 1 # 熔断器半开时允许运行的请求数量 默认设置为：1，请求成功则断路器关闭
  interval: 600 # 熔断器处于关闭状态时的清除周期，默认0，如果一直是关闭则不清除请求的次数信息
  timeout: 30 # 熔断器处于打开状态时，经过多久触发为半开状态，单位：s
  rule_type: 1 # 熔断类型：1连续错误达到阈值熔断，2错误率达到固定百分比熔断，3连续错误次数达到阈值或错误率达到阈值熔断，4连续错误次数达到阈值和错误率同时达到阈值熔断
  request_timeout: 5 # SideCar代理请求超时时间，单位：s
  btype: 1 #熔断粒度1,path单个实例下接口级别，2,host单个实例级别，默认接口级别
  cycle: 1 # 定时感应配置周期，单位：s

TraceConfig:
  trace_type: "skywalking"
  reporter_url: "192.168.64.6:30484"

DingTalkConfig:
  enable: true
  tokens: "264a82cac2e8bb0c1a23f3d320961d7d55b94f3e3f917b1eb479e5b8e0444a3e"
  secret: "SECa2d3c6fdab75eacc83ea49d9370830b57198a4bb5002f9bd9fe47f9866a9d4f7"

Prometheus:
  enable: true
  host: "0.0.0.0"
  port: "9081"
  path: "/metrics"

Dashboard:
  enable: true
  host: "0.0.0.0"
  port: "9082"
  default_path: "/dashboard"